package CanShop.POJOS;
// Generated Nov 16, 2017 3:07:22 PM by Hibernate Tools 4.3.1



/**
 * AdminOrderedProducts generated by hbm2java
 */
public class AdminOrderedProducts  implements java.io.Serializable {


     private Integer adminOrderedProductsId;
     private Products products;
     private String adminOrderedProductsUserName;
     private String adminOrderedProductsDate;
     private String adminOrderedProductsAmount;

    public AdminOrderedProducts() {
    }

    public AdminOrderedProducts(Products products, String adminOrderedProductsUserName, String adminOrderedProductsDate, String adminOrderedProductsAmount) {
       this.products = products;
       this.adminOrderedProductsUserName = adminOrderedProductsUserName;
       this.adminOrderedProductsDate = adminOrderedProductsDate;
       this.adminOrderedProductsAmount = adminOrderedProductsAmount;
    }
   
    public Integer getAdminOrderedProductsId() {
        return this.adminOrderedProductsId;
    }
    
    public void setAdminOrderedProductsId(Integer adminOrderedProductsId) {
        this.adminOrderedProductsId = adminOrderedProductsId;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public String getAdminOrderedProductsUserName() {
        return this.adminOrderedProductsUserName;
    }
    
    public void setAdminOrderedProductsUserName(String adminOrderedProductsUserName) {
        this.adminOrderedProductsUserName = adminOrderedProductsUserName;
    }
    public String getAdminOrderedProductsDate() {
        return this.adminOrderedProductsDate;
    }
    
    public void setAdminOrderedProductsDate(String adminOrderedProductsDate) {
        this.adminOrderedProductsDate = adminOrderedProductsDate;
    }
    public String getAdminOrderedProductsAmount() {
        return this.adminOrderedProductsAmount;
    }
    
    public void setAdminOrderedProductsAmount(String adminOrderedProductsAmount) {
        this.adminOrderedProductsAmount = adminOrderedProductsAmount;
    }




}


