package CanShop.POJOS;
// Generated Nov 16, 2017 3:07:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer cartId;
     private User user;
     private Set<OrderedProudcts> orderedProudctses = new HashSet<OrderedProudcts>(0);

    public Cart() {
    }

	
    public Cart(User user) {
        this.user = user;
    }
    public Cart(User user, Set<OrderedProudcts> orderedProudctses) {
       this.user = user;
       this.orderedProudctses = orderedProudctses;
    }
   
    public Integer getCartId() {
        return this.cartId;
    }
    
    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set<OrderedProudcts> getOrderedProudctses() {
        return this.orderedProudctses;
    }
    
    public void setOrderedProudctses(Set<OrderedProudcts> orderedProudctses) {
        this.orderedProudctses = orderedProudctses;
    }




}


