package CanShop.POJOS;
// Generated Nov 16, 2017 3:07:22 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OrderedProudcts generated by hbm2java
 */
public class OrderedProudcts  implements java.io.Serializable {


     private Integer orderedProductsId;
     private Cart cart;
     private Products products;
     private int productQuantity;
     private Date orderedProudctsDate;

    public OrderedProudcts() {
    }

    public OrderedProudcts(Cart cart, Products products, int productQuantity, Date orderedProudctsDate) {
       this.cart = cart;
       this.products = products;
       this.productQuantity = productQuantity;
       this.orderedProudctsDate = orderedProudctsDate;
    }
   
    public Integer getOrderedProductsId() {
        return this.orderedProductsId;
    }
    
    public void setOrderedProductsId(Integer orderedProductsId) {
        this.orderedProductsId = orderedProductsId;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public int getProductQuantity() {
        return this.productQuantity;
    }
    
    public void setProductQuantity(int productQuantity) {
        this.productQuantity = productQuantity;
    }
    public Date getOrderedProudctsDate() {
        return this.orderedProudctsDate;
    }
    
    public void setOrderedProudctsDate(Date orderedProudctsDate) {
        this.orderedProudctsDate = orderedProudctsDate;
    }




}


