package CanShop.POJOS;
// Generated Nov 16, 2017 3:07:22 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

    private Integer productId;
    private Category category;
    private Subcategory subcategory;
    private String productName;
    private int productPrice;
    private Integer productNprice;
    private int productAmount;
    private int productViewer;
    private int productOrdersNo;
    private String productDescription;
    private String productBrand;
    private Date productDate;
    private String productDimentions;
    private String productSerialNo;
    private Boolean productHotOffer;
    private String productArabicName;
    private String productArabicDescription;
    private String productArabicBrand;
    private Boolean productFeatured;
    private Set<AdminOrderedProducts> adminOrderedProductses = new HashSet<AdminOrderedProducts>(0);
    private Set<OrderedProudcts> orderedProudctses = new HashSet<OrderedProudcts>(0);

    public Products() {
    }

    public Products(Category category, String productName, int productPrice, int productAmount, int productViewer, int productOrdersNo, String productArabicName) {
        this.category = category;
        this.productName = productName;
        this.productPrice = productPrice;
        this.productAmount = productAmount;
        this.productViewer = productViewer;
        this.productOrdersNo = productOrdersNo;
        this.productArabicName = productArabicName;
    }

    public Products(Category category, Subcategory subcategory, String productName, int productPrice, Integer productNprice, int productAmount, int productViewer, int productOrdersNo, String productDescription, String productBrand, Date productDate, String productDimentions, String productSerialNo, Boolean productHotOffer, String productArabicName, String productArabicDescription, String productArabicBrand, Boolean productFeatured, Set<AdminOrderedProducts> adminOrderedProductses, Set<OrderedProudcts> orderedProudctses) {
        this.category = category;
        this.subcategory = subcategory;
        this.productName = productName;
        this.productPrice = productPrice;
        this.productNprice = productNprice;
        this.productAmount = productAmount;
        this.productViewer = productViewer;
        this.productOrdersNo = productOrdersNo;
        this.productDescription = productDescription;
        this.productBrand = productBrand;
        this.productDate = productDate;
        this.productDimentions = productDimentions;
        this.productSerialNo = productSerialNo;
        this.productHotOffer = productHotOffer;
        this.productArabicName = productArabicName;
        this.productArabicDescription = productArabicDescription;
        this.productArabicBrand = productArabicBrand;
        this.productFeatured = productFeatured;
        this.adminOrderedProductses = adminOrderedProductses;
        this.orderedProudctses = orderedProudctses;
    }

    public Products(Category category, Subcategory subcategory, String productName, int productPrice, Integer productNprice, int productAmount, int productViewer, int productOrdersNo, String productDescription, String productBrand, Date productDate, String productDimentions, String productSerialNo, Boolean productHotOffer, String productArabicName, String productArabicDescription, String productArabicBrand, Boolean productFeatured) {
        this.category = category;
        this.subcategory = subcategory;
        this.productName = productName;
        this.productPrice = productPrice;
        this.productNprice = productNprice;
        this.productAmount = productAmount;
        this.productViewer = productViewer;
        this.productOrdersNo = productOrdersNo;
        this.productDescription = productDescription;
        this.productBrand = productBrand;
        this.productDate = productDate;
        this.productDimentions = productDimentions;
        this.productSerialNo = productSerialNo;
        this.productHotOffer = productHotOffer;
        this.productArabicName = productArabicName;
        this.productArabicDescription = productArabicDescription;
        this.productArabicBrand = productArabicBrand;
        this.productFeatured = productFeatured;
    }

    public Integer getProductId() {
        return this.productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public Subcategory getSubcategory() {
        return this.subcategory;
    }

    public void setSubcategory(Subcategory subcategory) {
        this.subcategory = subcategory;
    }

    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public int getProductPrice() {
        return this.productPrice;
    }

    public void setProductPrice(int productPrice) {
        this.productPrice = productPrice;
    }

    public Integer getProductNprice() {
        return this.productNprice;
    }

    public void setProductNprice(Integer productNprice) {
        this.productNprice = productNprice;
    }

    public int getProductAmount() {
        return this.productAmount;
    }

    public void setProductAmount(int productAmount) {
        this.productAmount = productAmount;
    }

    public int getProductViewer() {
        return this.productViewer;
    }

    public void setProductViewer(int productViewer) {
        this.productViewer = productViewer;
    }

    public int getProductOrdersNo() {
        return this.productOrdersNo;
    }

    public void setProductOrdersNo(int productOrdersNo) {
        this.productOrdersNo = productOrdersNo;
    }

    public String getProductDescription() {
        return this.productDescription;
    }

    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    public String getProductBrand() {
        return this.productBrand;
    }

    public void setProductBrand(String productBrand) {
        this.productBrand = productBrand;
    }

    public Date getProductDate() {
        return this.productDate;
    }

    public void setProductDate(Date productDate) {
        this.productDate = productDate;
    }

    public String getProductDimentions() {
        return this.productDimentions;
    }

    public void setProductDimentions(String productDimentions) {
        this.productDimentions = productDimentions;
    }

    public String getProductSerialNo() {
        return this.productSerialNo;
    }

    public void setProductSerialNo(String productSerialNo) {
        this.productSerialNo = productSerialNo;
    }

    public Boolean getProductHotOffer() {
        return this.productHotOffer;
    }

    public void setProductHotOffer(Boolean productHotOffer) {
        this.productHotOffer = productHotOffer;
    }

    public String getProductArabicName() {
        return this.productArabicName;
    }

    public void setProductArabicName(String productArabicName) {
        this.productArabicName = productArabicName;
    }

    public String getProductArabicDescription() {
        return this.productArabicDescription;
    }

    public void setProductArabicDescription(String productArabicDescription) {
        this.productArabicDescription = productArabicDescription;
    }

    public String getProductArabicBrand() {
        return this.productArabicBrand;
    }

    public void setProductArabicBrand(String productArabicBrand) {
        this.productArabicBrand = productArabicBrand;
    }

    public Boolean getProductFeatured() {
        return this.productFeatured;
    }

    public void setProductFeatured(Boolean productFeatured) {
        this.productFeatured = productFeatured;
    }

    public Set<AdminOrderedProducts> getAdminOrderedProductses() {
        return this.adminOrderedProductses;
    }

    public void setAdminOrderedProductses(Set<AdminOrderedProducts> adminOrderedProductses) {
        this.adminOrderedProductses = adminOrderedProductses;
    }

    public Set<OrderedProudcts> getOrderedProudctses() {
        return this.orderedProudctses;
    }

    public void setOrderedProudctses(Set<OrderedProudcts> orderedProudctses) {
        this.orderedProudctses = orderedProudctses;
    }

}
