package CanShop.POJOS;
// Generated Nov 16, 2017 3:07:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subcategory generated by hbm2java
 */
public class Subcategory  implements java.io.Serializable {


     private Integer subCategoryId;
     private Category category;
     private String subCategoryName;
     private String subCategoryArabicName;
     private Set<Products> productses = new HashSet<Products>(0);

    public Subcategory() {
    }

	
    public Subcategory(Category category, String subCategoryName, String subCategoryArabicName) {
        this.category = category;
        this.subCategoryName = subCategoryName;
        this.subCategoryArabicName = subCategoryArabicName;
    }
    public Subcategory(Category category, String subCategoryName, String subCategoryArabicName, Set<Products> productses) {
       this.category = category;
       this.subCategoryName = subCategoryName;
       this.subCategoryArabicName = subCategoryArabicName;
       this.productses = productses;
    }
   
    public Integer getSubCategoryId() {
        return this.subCategoryId;
    }
    
    public void setSubCategoryId(Integer subCategoryId) {
        this.subCategoryId = subCategoryId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getSubCategoryName() {
        return this.subCategoryName;
    }
    
    public void setSubCategoryName(String subCategoryName) {
        this.subCategoryName = subCategoryName;
    }
    public String getSubCategoryArabicName() {
        return this.subCategoryArabicName;
    }
    
    public void setSubCategoryArabicName(String subCategoryArabicName) {
        this.subCategoryArabicName = subCategoryArabicName;
    }
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


